---
networks:
  proxy:
    driver: bridge
    external: true
  secure:
    driver: bridge
    external: true

services:
  dockersocket:
    restart: unless-stopped
    environment:
      - AUTH=0
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISABLE_IPV6=0
      - DISTRIBUTION=0
      - EVENTS=1
      - EXEC=0
      - IMAGES=0
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PING=1
      - POST=0
      - PLUGINS=0
      - SECRETS=0
      - SERVICES=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=0
      - VERSION=1
      - VOLUMES=0
    privileged: true
    read_only: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run
    networks:
      - secure

  traefik:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${CURDIR}/.data/traefik/ssl/:/etc/traefik/ssl/
      - ${CURDIR}/.logs/traefik/:/var/log/traefik/
    environment:
      - DOCKER_HOST=dockersocket
    ports:
      - target: 80
        published: ${TRAEFIK_HOST_HTTP_PORT:-80}
        protocol: tcp
        mode: host
      - target: 443
        published: ${TRAEFIK_HOST_HTTPS_PORT:-443}
        protocol: tcp
        mode: host
      - target: 9443
        published: ${TRAEFIK_HOST_CMK_AGENT_PORT:-9443}
        protocol: tcp
        mode: host
    networks:
      - secure
      - proxy
    depends_on:
      - dockersocket

  logger:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${CURDIR}/.logs/traefik:/var/log/traefik
    networks:
      - secure
    depends_on:
      - traefik

  checkmk:
    image: docker.io/checkmk/check-mk-raw:${CHECKMK_VERSION?}
    restart: unless-stopped
    networks:
      - secure
    environment:
      - TZ=${TIMEZONE:-Asia/Jakarta}
      - CMK_PASSWORD=${CHECKMK_ADMIN_PASSWORD?}
      - CMK_SITE_ID=${CHECKMK_SITE_ID?}
      - CMK_LIVESTATUS_TCP=on
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CURDIR}/.data/checkmk:/omd/sites
    tmpfs:
      - /opt/omd/sites/${CHECKMK_SITE_ID?}/tmp:uid=${CHECKMK_USER_ID:-1000},gid=${CHECKMK_GROUP_ID:-1000}
    ulimits:
      nofile: 1024
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - traefik.enable=true
      - traefik.http.routers.checkmk.rule=Host(`${CHECKMK_DOMAIN_NAME}`)
      - traefik.http.routers.checkmk.service=noop@internal
      - traefik.http.routers.checkmk.entrypoints=https
      - traefik.http.services.checkmk.loadbalancer.server.port=5000
      - traefik.http.routers.checkmk_agent.rule=Host(`${CHECKMK_DOMAIN_NAME}`)
      - traefik.http.routers.checkmk_agent.service=noop@internal
      - traefik.http.routers.checkmk_agent.entrypoints=cmkAgent
      - traefik.http.services.checkmk_agent.loadbalancer.server.port=8000
