global:
  checkNewVersion: false
  sendAnonymousUsage: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
# Not used in apps, but redirect everything from HTTP to HTTPS
  http:
    address: :80
    forwardedHeaders:
      trustedIPs:
        &trustedIps # Start of Clouflare public IP list for HTTP requests, remove this if you don't use it
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 108.162.192.0/18
        - 131.0.72.0/22
        - 141.101.64.0/18
        - 162.158.0.0/15
        - 172.64.0.0/13
        - 173.245.48.0/20
        - 188.114.96.0/20
        - 190.93.240.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
        # End of Cloudlare public IP list
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  # HTTPS endpoint, with domain wildcard
  https:
    address: :443
    forwardedHeaders:
      # Reuse list of Cloudflare Trusted IP's above for HTTPS requests
      trustedIPs: *trustedIps
    http:
      tls:
        # Generate a wildcard domain certificate
        certResolver: letsEncrypt
        domains:
          - main: domain.com
            sans:
              - "*.domain.com"
      middlewares:
        - default@file

  # Checkmk custom HTTPS endpoint, with domain wildcard
  agentHttps:
    address: :9443
    forwardedHeaders:
      # Reuse list of Cloudflare Trusted IP's above for HTTPS requests
      trustedIPs: *trustedIps
    http:
      tls:
        # Generate a wildcard domain certificate
        certResolver: letsEncrypt
        domains:
          - main: domain.com
            sans:
              - "*.domain.com"
      middlewares:
        - default@file

certificatesResolvers:
  letsEncrypt:
    acme:
      email: email@mail.com
      storage: /etc/traefik/ssl/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  providersThrottleDuration: 2s
  # File provider for connecting things that are outside of docker / defining middleware
  file:
    directory: /etc/traefik/dynamic/
    watch: true
  # Docker provider for connecting all apps that are inside of the docker network
  docker:
    endpoint: "tcp://dockerproxy:2375"
    network: securenet
    exposedByDefault: false
    # swarmModeRefreshSeconds: 15s
    watch: true

# Enable traefik ui
api:
  dashboard: true
  insecure: false

# Log level INFO|DEBUG|ERROR
log:
  level: INFO
  maxSize: 100
  maxBackups: 3
  maxAge: 3
  compress: true

accessLog:
  filePath: /var/log/traefik/access.log
  bufferingSize: 100
  format: json
  filters:
    statusCodes:
      - "200"
      - "300-302"
    retryAttempts: true
    minDuration: "10ms"
  fields:
    names:
      StartUTC: drop
